### ISSUE TITLE
Termina el ejercicio!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-libertadcc#1]
Buen trabajo @libertadcc !

Algunas pistas para acabarlo:

- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: un div o article que la englobe (mira el error que tienes en consola) y una imagen para mostrar el Pokemon
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Mueve el `li` fuera del componente 'Pokemon' (cuando lo hagas), de esta manera Pokemon es un componente con una tarjeta que podemos usar en sitios y no solo dentro de un `ul`
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Elimina el código comentado
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usary sus referencias

Si tienes cualquier duda, avisa!

Al turrón

**Comment by libertadcc** [comment]
He intentado publicar en Github Pages de todos los métodos posibles pero se me resiste

**Comment by libertadcc** [comment]
He conseguido publicarlo y he añadido un array con los datos

**Comment by oneeyedman** [comment]
Hola, @libertadcc : Faltaría apañar el tema de los PropTypes!

**Comment by libertadcc** [comment]
Hola @oneeyedman, creo que ya sí !

**Comment by oneeyedman** [comment]
Venga! Terminado! Buen trabajo, @libertadcc!!
